name: proyecto_de_prueba
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  math_expressions: ^2.2.0
  flutter_tex: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/files/
    - assets/JSON/

  uses-material-design: true

